apiVersion: apps/v1
kind: Deployment
metadata: 
  name: event-bus-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: bujosa/event-bus
