apiVersion: apps/v1
kind: Deployment
metadata: 
  name: events-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: bujosa/event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: events-service   
spec:
  type: NodePort
  selector:
    app: events
  ports:
    - name: events
      protocol: TCP
      port: 4005
      targetPort: 4005
